baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Antonio Minondo's Blog"
theme = "simple-a"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "about/"

[[menu.main]]
    name = "Contact"
    url = "contact/"
    
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aminondo/iX-DS-Blog"

[params]
    description = "A blog for my iXperience Data Science Class!"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

