baseurl = "/"
languageCode = "en"
title = "Antonio Minondo's Blog"
theme = "hugo-zen"


[taxonomies]
tag = "tags"
category = "categories"

[params]
  logo = "images/profile.jpg"
  github    = "https://github.com/aminondo/"
  email     = "aminondo@nd.edu"

